Card game "21"
Tixon9I/Course_Pro pull request #2
Opened 2024-06-29 18:54 UTC by Tixon9I

2024-06-30 10:26 UTC, Delvin09 requested changes

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +            title = new string[] { "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
может лучше через enum?

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        public readonly string[] title;
Давай лучше через ридонли свойства.

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +    struct Cards
Разнеси по отдельным файлам

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private readonly string[] title;
Почему бы не сделать класс колода, в которой и будут карты распологатся?

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private int sumPlayer = 0;
Создай для статистики отдельный класс

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +            var positionAces = new string[5];
В колоде 5ть тузов?

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        // Метод, де відбувається цикл гри
делай документирующие комметарии - это через ///

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        // Метод, де відбувається цикл гри
лучше сразу на англ

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +            if (countAcesPlayer == 2)
выглядит не очень...

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +                    ChooseCard(number, cards, 'p');
что значит 'p'?

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +                    if (exception == 2)
что значит 2?

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +                    if (exception == 2)
Мне кажется нужно это отрефакторить так, чтобы небыло магических значений

2024-06-30 10:26 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private List<string> cardsPlayer;
Можно также создать класс игрок, и инкапсулировать туда некоторую логику и данные

2024-06-30 18:51 UTC, Delvin09 requested changes

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Cards.cs
> +    internal class Cards
Еще чуть-чуть и будет норм:
- создай структуру Карта (Card) и вынеси в нее все что касается карты
- переименуй этот класс в Deck - тут останется все что касается колоды (в том числе и кол-ция карт)

А так у тебя получается что класс служит для двух задач

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Cards.cs
> +    internal class Cards
И еще, множественные сущности (классы, структуры и пр.) мы практически не используем. Т.е. с точки зрения проектирования, Card**s** нужно разбить на Card и Deck (или ListOfCards, или на чтото подобное)

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Cards.cs
> +        public readonly string[] title = new string[] { "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
После нормально разделение на Карту и Колоду, не будет необходимости использовать эти топорные массивы, и можно будет создать пару enum'ов - для значений и для масти. Значения можно легко переводить в int и обратно в enum.

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Players.cs
> +    internal class Players
Та же проблема что и с Картой/Картами

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Players.cs
> +    internal class Players
Игрок - это класс
Игроки - это объекты класса Игрок

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private Statistics statistics = new Statistics();
думаю статистика тоже readonly

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private string CheckResultPlayers()
А точно должна строка возвращаться? Выглядит это все не очень.
Я бы сделал проверку кто победил в сессии, и вернул бы объект игрока, или null - если победили оба.

После этого можно упростить условия ниже.

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private readonly List<KeyValuePair<string, int>> cardValue;
А теперь проставь _ перед именами полей (используй механизм переименования в VS - F2 или Ctrl+R+R)
И станет видно в коде, где поля, а где переменные. Особенно если использовать редактор в гитхабе.

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Program.cs
> +            Cards cards = new Cards();
Ничего не понимаю, почему со стороны создается колода карт и передается в МЕТОД игры? Мне кажется, что сама игра знает когда ей следует создать колоду, как и какую.
Так же со статистикой. Пусть игра создает статистику сама, А во вне остальные пусть используют ее.

2024-06-30 18:51 UTC, Delvin09 commented on C# Pro/CardGame/Statistics.cs
> +        public static List<string> statistics { get; set; }
Какая-то каша. У тебя статическое поле, а НЕ-статический конструктор это поле каждый раз заполняет другим объектом. Т.е. на каждый new Statistics у тебя обнулится список.
Я бы понял если бы весь класс был статический. А так ни туда ни сюда.
Идея статистики был сбор кол-ва побед и пр. по всем матчам. А тут список строк...

2024-06-30 19:00 UTC, Delvin09 commented
А еще ты можешь мои коменты помечать как resolved или както так.

2024-06-30 22:05 UTC, Tixon9I commented on C# Pro/CardGame/Cards.cs
> +    internal class Cards
resolved

2024-06-30 22:06 UTC, Tixon9I commented on C# Pro/CardGame/Players.cs
> +    internal class Players
resolved

2024-07-01 11:16 UTC, Tixon9I commented on C# Pro/CardGame/Program.cs
> +            Cards cards = new Cards();
resolved

2024-07-01 11:16 UTC, Tixon9I commented on C# Pro/CardGame/Statistics.cs
> +        public static List<string> statistics { get; set; }
resolved

2024-07-01 11:16 UTC, Tixon9I commented on C# Pro/CardGame/CardGame.cs
> +        private readonly List<KeyValuePair<string, int>> cardValue;
resolved

2024-07-01 11:16 UTC, Tixon9I commented on C# Pro/CardGame/CardGame.cs
> +        private string CheckResultPlayers()
resolved

2024-07-01 11:17 UTC, Tixon9I commented on C# Pro/CardGame/Cards.cs
> +        public readonly string[] title = new string[] { "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
resolved

2024-07-01 13:18 UTC, Delvin09 requested changes

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +            _player._cardsPlayer.Clear();
_player.Clear() - а там уже пусть очищает свою кол-цию

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +                _player._sumPlayer = GetCardValue(cards[index]) + GetCardValue(cards[++index]);
Пусть игрок сам подсчитывает очки своих карт

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/Player.cs
> +        public int _sumPlayer { get; set; }
Свойства не поля, их стоит называть с большой буквы без подчеркивания, как методы.
_sumPlayer - можно сделать вычисляемым, так-как карты у игрока есть, пройтись по ним и посчитать

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/Player.cs
> +        public List<string> _cardsPlayer { get; set; }
убери сеттер

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/Deck.cs
> +        J,
Можно назвать полными именами, так будет понятнее в коде + можно потом конвертировать в строки при выводе

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/Deck.cs
> +    enum Title
Вынеси enum'ы в отдельные файлы тоже

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/Deck.cs
> +        public List<Card> _cards = new List<Card>();
private

2024-07-01 13:18 UTC, Delvin09 commented on C# Pro/CardGame/CardGame.cs
> +        private readonly List<KeyValuePair<string, int>> _cardValue;
значения можно брать из enum'a

2024-07-01 13:20 UTC, Delvin09 requested changes

2024-07-01 13:20 UTC, Delvin09 commented on C# Pro/CardGame/Deck.cs
> +        public readonly Title _title;
если поля открыты (public) лучше тоже без подчеркивания и с большой

2024-07-01 14:31 UTC, Tixon9I commented on C# Pro/CardGame/CardGame.cs
> +            _player._cardsPlayer.Clear();
resolved

2024-07-01 14:31 UTC, Tixon9I commented on C# Pro/CardGame/CardGame.cs
> +                _player._sumPlayer = GetCardValue(cards[index]) + GetCardValue(cards[++index]);
resolved

2024-07-01 14:53 UTC, Tixon9I commented on C# Pro/CardGame/Player.cs
> +        public int _sumPlayer { get; set; }
resolved

2024-07-01 14:55 UTC, Tixon9I commented on C# Pro/CardGame/Deck.cs
> +    enum Title
resolved

2024-07-01 14:55 UTC, Tixon9I commented on C# Pro/CardGame/CardGame.cs
> +        private readonly List<KeyValuePair<string, int>> _cardValue;
resolved

2024-07-01 14:57 UTC, Tixon9I commented on C# Pro/CardGame/Deck.cs
> +        public List<Card> _cards = new List<Card>();
resolved

2024-07-01 15:08 UTC, Tixon9I commented on C# Pro/CardGame/Deck.cs
> +        J,
resolved

2024-07-01 15:12 UTC, Tixon9I commented on C# Pro/CardGame/Player.cs
> +        public List<string> _cardsPlayer { get; set; }
resolved

2024-07-01 18:47 UTC, merged